builds:
  - binary: prestd
    main: ./cmd/prestd/main.go
    ldflags: -X github.com/prest/prest/helpers.PrestVersionNumber={{.Version}} -X github.com/prest/prest/helpers.CommitHash={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mipsle
      - mips64le
      - ppc64
      - ppc64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
dockers:
  binaries: prestd
  image_templates: "prest/prest:{{ .Tag }}"
  extra_files: cmd/prestd/prest.toml
release:
  github:
    owner: prest
    name: prest
