builds:
  - binary: prest
    main: main.go
    ldflags: -X github.com/prest/prest/vendor/github.com/prest/helpers.PrestVersionNumber={{.Version}} -X github.com/prest/prest/vendor/github.com/prest/helpers.CommitHash={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mipsle
      - mips64le
      - ppc64
      - ppc64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
dockers:
- image: prest/prest
  tag_templates:
    - '{{ .Tag }}'
release:
  github:
    owner: prest
    name: prest