---
engines:
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - go
exclude_paths:
- vendor/
