// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: Adapter)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	context "context"
	sql "database/sql"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	adapters "github.com/prest/prest/v2/adapters"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// Aliases mocks base method.
func (m *MockAdapter) Aliases() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aliases")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Aliases indicates an expected call of Aliases.
func (mr *MockAdapterMockRecorder) Aliases() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aliases", reflect.TypeOf((*MockAdapter)(nil).Aliases))
}

// BatchInsertCopy mocks base method.
func (m *MockAdapter) BatchInsertCopy(arg0, arg1, arg2 string, arg3 []string, arg4 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchInsertCopy", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// BatchInsertCopy indicates an expected call of BatchInsertCopy.
func (mr *MockAdapterMockRecorder) BatchInsertCopy(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertCopy", reflect.TypeOf((*MockAdapter)(nil).BatchInsertCopy), varargs...)
}

// BatchInsertCopyCtx mocks base method.
func (m *MockAdapter) BatchInsertCopyCtx(arg0 context.Context, arg1, arg2, arg3 string, arg4 []string, arg5 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchInsertCopyCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// BatchInsertCopyCtx indicates an expected call of BatchInsertCopyCtx.
func (mr *MockAdapterMockRecorder) BatchInsertCopyCtx(arg0, arg1, arg2, arg3, arg4 interface{}, arg5 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertCopyCtx", reflect.TypeOf((*MockAdapter)(nil).BatchInsertCopyCtx), varargs...)
}

// BatchInsertValues mocks base method.
func (m *MockAdapter) BatchInsertValues(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchInsertValues", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// BatchInsertValues indicates an expected call of BatchInsertValues.
func (mr *MockAdapterMockRecorder) BatchInsertValues(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertValues", reflect.TypeOf((*MockAdapter)(nil).BatchInsertValues), varargs...)
}

// BatchInsertValuesCtx mocks base method.
func (m *MockAdapter) BatchInsertValuesCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchInsertValuesCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// BatchInsertValuesCtx indicates an expected call of BatchInsertValuesCtx.
func (mr *MockAdapterMockRecorder) BatchInsertValuesCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertValuesCtx", reflect.TypeOf((*MockAdapter)(nil).BatchInsertValuesCtx), varargs...)
}

// CountByRequest mocks base method.
func (m *MockAdapter) CountByRequest(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByRequest indicates an expected call of CountByRequest.
func (mr *MockAdapterMockRecorder) CountByRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByRequest", reflect.TypeOf((*MockAdapter)(nil).CountByRequest), arg0)
}

// DatabaseClause mocks base method.
func (m *MockAdapter) DatabaseClause(arg0 *http.Request) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseClause", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DatabaseClause indicates an expected call of DatabaseClause.
func (mr *MockAdapterMockRecorder) DatabaseClause(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseClause", reflect.TypeOf((*MockAdapter)(nil).DatabaseClause), arg0)
}

// DatabaseOrderBy mocks base method.
func (m *MockAdapter) DatabaseOrderBy(arg0 string, arg1 bool) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseOrderBy", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// DatabaseOrderBy indicates an expected call of DatabaseOrderBy.
func (mr *MockAdapterMockRecorder) DatabaseOrderBy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseOrderBy", reflect.TypeOf((*MockAdapter)(nil).DatabaseOrderBy), arg0, arg1)
}

// DatabaseWhere mocks base method.
func (m *MockAdapter) DatabaseWhere(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseWhere", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// DatabaseWhere indicates an expected call of DatabaseWhere.
func (mr *MockAdapterMockRecorder) DatabaseWhere(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseWhere", reflect.TypeOf((*MockAdapter)(nil).DatabaseWhere), arg0)
}

// Delete mocks base method.
func (m *MockAdapter) Delete(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdapterMockRecorder) Delete(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdapter)(nil).Delete), varargs...)
}

// DeleteCtx mocks base method.
func (m *MockAdapter) DeleteCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// DeleteCtx indicates an expected call of DeleteCtx.
func (mr *MockAdapterMockRecorder) DeleteCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCtx", reflect.TypeOf((*MockAdapter)(nil).DeleteCtx), varargs...)
}

// DeleteSQL mocks base method.
func (m *MockAdapter) DeleteSQL(arg0, arg1, arg2 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSQL", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	return ret0
}

// DeleteSQL indicates an expected call of DeleteSQL.
func (mr *MockAdapterMockRecorder) DeleteSQL(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSQL", reflect.TypeOf((*MockAdapter)(nil).DeleteSQL), arg0, arg1, arg2)
}

// DeleteWithTransaction mocks base method.
func (m *MockAdapter) DeleteWithTransaction(arg0 *sql.Tx, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteWithTransaction", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// DeleteWithTransaction indicates an expected call of DeleteWithTransaction.
func (mr *MockAdapterMockRecorder) DeleteWithTransaction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTransaction", reflect.TypeOf((*MockAdapter)(nil).DeleteWithTransaction), varargs...)
}

// DistinctClause mocks base method.
func (m *MockAdapter) DistinctClause(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistinctClause", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistinctClause indicates an expected call of DistinctClause.
func (mr *MockAdapterMockRecorder) DistinctClause(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistinctClause", reflect.TypeOf((*MockAdapter)(nil).DistinctClause), arg0)
}

// ExecuteScripts mocks base method.
func (m *MockAdapter) ExecuteScripts(arg0, arg1 string, arg2 []interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteScripts", arg0, arg1, arg2)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ExecuteScripts indicates an expected call of ExecuteScripts.
func (mr *MockAdapterMockRecorder) ExecuteScripts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteScripts", reflect.TypeOf((*MockAdapter)(nil).ExecuteScripts), arg0, arg1, arg2)
}

// ExecuteScriptsCtx mocks base method.
func (m *MockAdapter) ExecuteScriptsCtx(arg0 context.Context, arg1, arg2 string, arg3 []interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteScriptsCtx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ExecuteScriptsCtx indicates an expected call of ExecuteScriptsCtx.
func (mr *MockAdapterMockRecorder) ExecuteScriptsCtx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteScriptsCtx", reflect.TypeOf((*MockAdapter)(nil).ExecuteScriptsCtx), arg0, arg1, arg2, arg3)
}

// FieldsPermissions mocks base method.
func (m *MockAdapter) FieldsPermissions(arg0 *http.Request, arg1, arg2, arg3, arg4, arg5 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FieldsPermissions", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FieldsPermissions indicates an expected call of FieldsPermissions.
func (mr *MockAdapterMockRecorder) FieldsPermissions(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FieldsPermissions", reflect.TypeOf((*MockAdapter)(nil).FieldsPermissions), arg0, arg1, arg2, arg3, arg4, arg5)
}

// GetDatabase mocks base method.
func (m *MockAdapter) GetDatabase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabase")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockAdapterMockRecorder) GetDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabase", reflect.TypeOf((*MockAdapter)(nil).GetDatabase))
}

// GetScript mocks base method.
func (m *MockAdapter) GetScript(arg0, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScript", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScript indicates an expected call of GetScript.
func (mr *MockAdapterMockRecorder) GetScript(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScript", reflect.TypeOf((*MockAdapter)(nil).GetScript), arg0, arg1, arg2)
}

// GetTransaction mocks base method.
func (m *MockAdapter) GetTransaction() (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction")
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockAdapterMockRecorder) GetTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockAdapter)(nil).GetTransaction))
}

// GetTransactionCtx mocks base method.
func (m *MockAdapter) GetTransactionCtx(arg0 context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionCtx", arg0)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionCtx indicates an expected call of GetTransactionCtx.
func (mr *MockAdapterMockRecorder) GetTransactionCtx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionCtx", reflect.TypeOf((*MockAdapter)(nil).GetTransactionCtx), arg0)
}

// GroupByClause mocks base method.
func (m *MockAdapter) GroupByClause(arg0 *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupByClause", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GroupByClause indicates an expected call of GroupByClause.
func (mr *MockAdapterMockRecorder) GroupByClause(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupByClause", reflect.TypeOf((*MockAdapter)(nil).GroupByClause), arg0)
}

// Insert mocks base method.
func (m *MockAdapter) Insert(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAdapterMockRecorder) Insert(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAdapter)(nil).Insert), varargs...)
}

// InsertCtx mocks base method.
func (m *MockAdapter) InsertCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// InsertCtx indicates an expected call of InsertCtx.
func (mr *MockAdapterMockRecorder) InsertCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCtx", reflect.TypeOf((*MockAdapter)(nil).InsertCtx), varargs...)
}

// InsertSQL mocks base method.
func (m *MockAdapter) InsertSQL(arg0, arg1, arg2, arg3, arg4 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSQL", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	return ret0
}

// InsertSQL indicates an expected call of InsertSQL.
func (mr *MockAdapterMockRecorder) InsertSQL(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSQL", reflect.TypeOf((*MockAdapter)(nil).InsertSQL), arg0, arg1, arg2, arg3, arg4)
}

// InsertWithTransaction mocks base method.
func (m *MockAdapter) InsertWithTransaction(arg0 *sql.Tx, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertWithTransaction", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// InsertWithTransaction indicates an expected call of InsertWithTransaction.
func (mr *MockAdapterMockRecorder) InsertWithTransaction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithTransaction", reflect.TypeOf((*MockAdapter)(nil).InsertWithTransaction), varargs...)
}

// IsRegistered mocks base method.
func (m *MockAdapter) IsRegistered(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRegistered", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRegistered indicates an expected call of IsRegistered.
func (mr *MockAdapterMockRecorder) IsRegistered(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRegistered", reflect.TypeOf((*MockAdapter)(nil).IsRegistered), arg0)
}

// JoinByRequest mocks base method.
func (m *MockAdapter) JoinByRequest(arg0 *http.Request) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinByRequest", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinByRequest indicates an expected call of JoinByRequest.
func (mr *MockAdapterMockRecorder) JoinByRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinByRequest", reflect.TypeOf((*MockAdapter)(nil).JoinByRequest), arg0)
}

// OrderByRequest mocks base method.
func (m *MockAdapter) OrderByRequest(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderByRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderByRequest indicates an expected call of OrderByRequest.
func (mr *MockAdapterMockRecorder) OrderByRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderByRequest", reflect.TypeOf((*MockAdapter)(nil).OrderByRequest), arg0)
}

// PaginateIfPossible mocks base method.
func (m *MockAdapter) PaginateIfPossible(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaginateIfPossible", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PaginateIfPossible indicates an expected call of PaginateIfPossible.
func (mr *MockAdapterMockRecorder) PaginateIfPossible(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaginateIfPossible", reflect.TypeOf((*MockAdapter)(nil).PaginateIfPossible), arg0)
}

// ParseBatchInsertRequest mocks base method.
func (m *MockAdapter) ParseBatchInsertRequest(arg0 *http.Request) (string, string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseBatchInsertRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].([]interface{})
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ParseBatchInsertRequest indicates an expected call of ParseBatchInsertRequest.
func (mr *MockAdapterMockRecorder) ParseBatchInsertRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseBatchInsertRequest", reflect.TypeOf((*MockAdapter)(nil).ParseBatchInsertRequest), arg0)
}

// ParseInsertRequest mocks base method.
func (m *MockAdapter) ParseInsertRequest(arg0 *http.Request) (string, string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInsertRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].([]interface{})
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ParseInsertRequest indicates an expected call of ParseInsertRequest.
func (mr *MockAdapterMockRecorder) ParseInsertRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInsertRequest", reflect.TypeOf((*MockAdapter)(nil).ParseInsertRequest), arg0)
}

// ParseScript mocks base method.
func (m *MockAdapter) ParseScript(arg0 string, arg1 map[string]interface{}) (string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseScript", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParseScript indicates an expected call of ParseScript.
func (mr *MockAdapterMockRecorder) ParseScript(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseScript", reflect.TypeOf((*MockAdapter)(nil).ParseScript), arg0, arg1)
}

// ParseScriptTemplate mocks base method.
func (m *MockAdapter) ParseScriptTemplate(arg0, arg1 string, arg2 map[string]interface{}) (string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseScriptTemplate", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParseScriptTemplate indicates an expected call of ParseScriptTemplate.
func (mr *MockAdapterMockRecorder) ParseScriptTemplate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseScriptTemplate", reflect.TypeOf((*MockAdapter)(nil).ParseScriptTemplate), arg0, arg1, arg2)
}

// PhysicalName mocks base method.
func (m *MockAdapter) PhysicalName(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhysicalName", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// PhysicalName indicates an expected call of PhysicalName.
func (mr *MockAdapterMockRecorder) PhysicalName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhysicalName", reflect.TypeOf((*MockAdapter)(nil).PhysicalName), arg0)
}

// Ping mocks base method.
func (m *MockAdapter) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockAdapterMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockAdapter)(nil).Ping), arg0)
}

// PingAll mocks base method.
func (m *MockAdapter) PingAll(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingAll", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingAll indicates an expected call of PingAll.
func (mr *MockAdapterMockRecorder) PingAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingAll", reflect.TypeOf((*MockAdapter)(nil).PingAll), arg0)
}

// Query mocks base method.
func (m *MockAdapter) Query(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockAdapterMockRecorder) Query(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockAdapter)(nil).Query), varargs...)
}

// QueryCount mocks base method.
func (m *MockAdapter) QueryCount(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCount", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// QueryCount indicates an expected call of QueryCount.
func (mr *MockAdapterMockRecorder) QueryCount(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCount", reflect.TypeOf((*MockAdapter)(nil).QueryCount), varargs...)
}

// QueryCountCtx mocks base method.
func (m *MockAdapter) QueryCountCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCountCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// QueryCountCtx indicates an expected call of QueryCountCtx.
func (mr *MockAdapterMockRecorder) QueryCountCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCountCtx", reflect.TypeOf((*MockAdapter)(nil).QueryCountCtx), varargs...)
}

// QueryCtx mocks base method.
func (m *MockAdapter) QueryCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// QueryCtx indicates an expected call of QueryCtx.
func (mr *MockAdapterMockRecorder) QueryCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCtx", reflect.TypeOf((*MockAdapter)(nil).QueryCtx), varargs...)
}

// ResolveScript mocks base method.
func (m *MockAdapter) ResolveScript(arg0 context.Context, arg1, arg2, arg3, arg4 string) (adapters.ScriptSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveScript", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(adapters.ScriptSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveScript indicates an expected call of ResolveScript.
func (mr *MockAdapterMockRecorder) ResolveScript(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveScript", reflect.TypeOf((*MockAdapter)(nil).ResolveScript), arg0, arg1, arg2, arg3, arg4)
}

// ReturningByRequest mocks base method.
func (m *MockAdapter) ReturningByRequest(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturningByRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReturningByRequest indicates an expected call of ReturningByRequest.
func (mr *MockAdapterMockRecorder) ReturningByRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturningByRequest", reflect.TypeOf((*MockAdapter)(nil).ReturningByRequest), arg0)
}

// SchemaClause mocks base method.
func (m *MockAdapter) SchemaClause(arg0 *http.Request) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaClause", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// SchemaClause indicates an expected call of SchemaClause.
func (mr *MockAdapterMockRecorder) SchemaClause(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaClause", reflect.TypeOf((*MockAdapter)(nil).SchemaClause), arg0)
}

// SchemaOrderBy mocks base method.
func (m *MockAdapter) SchemaOrderBy(arg0 string, arg1 bool) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaOrderBy", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// SchemaOrderBy indicates an expected call of SchemaOrderBy.
func (mr *MockAdapterMockRecorder) SchemaOrderBy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaOrderBy", reflect.TypeOf((*MockAdapter)(nil).SchemaOrderBy), arg0, arg1)
}

// SchemaTablesClause mocks base method.
func (m *MockAdapter) SchemaTablesClause() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaTablesClause")
	ret0, _ := ret[0].(string)
	return ret0
}

// SchemaTablesClause indicates an expected call of SchemaTablesClause.
func (mr *MockAdapterMockRecorder) SchemaTablesClause() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaTablesClause", reflect.TypeOf((*MockAdapter)(nil).SchemaTablesClause))
}

// SchemaTablesOrderBy mocks base method.
func (m *MockAdapter) SchemaTablesOrderBy(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaTablesOrderBy", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// SchemaTablesOrderBy indicates an expected call of SchemaTablesOrderBy.
func (mr *MockAdapterMockRecorder) SchemaTablesOrderBy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaTablesOrderBy", reflect.TypeOf((*MockAdapter)(nil).SchemaTablesOrderBy), arg0)
}

// SchemaTablesWhere mocks base method.
func (m *MockAdapter) SchemaTablesWhere(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaTablesWhere", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// SchemaTablesWhere indicates an expected call of SchemaTablesWhere.
func (mr *MockAdapterMockRecorder) SchemaTablesWhere(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaTablesWhere", reflect.TypeOf((*MockAdapter)(nil).SchemaTablesWhere), arg0)
}

// SelectFields mocks base method.
func (m *MockAdapter) SelectFields(arg0 []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectFields", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectFields indicates an expected call of SelectFields.
func (mr *MockAdapterMockRecorder) SelectFields(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectFields", reflect.TypeOf((*MockAdapter)(nil).SelectFields), arg0)
}

// SelectSQL mocks base method.
func (m *MockAdapter) SelectSQL(arg0, arg1, arg2, arg3 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectSQL", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectSQL indicates an expected call of SelectSQL.
func (mr *MockAdapterMockRecorder) SelectSQL(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectSQL", reflect.TypeOf((*MockAdapter)(nil).SelectSQL), arg0, arg1, arg2, arg3)
}

// SetByRequest mocks base method.
func (m *MockAdapter) SetByRequest(arg0 *http.Request, arg1 int) (string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByRequest", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetByRequest indicates an expected call of SetByRequest.
func (mr *MockAdapterMockRecorder) SetByRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByRequest", reflect.TypeOf((*MockAdapter)(nil).SetByRequest), arg0, arg1)
}

// SetDatabase mocks base method.
func (m *MockAdapter) SetDatabase(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDatabase", arg0)
}

// SetDatabase indicates an expected call of SetDatabase.
func (mr *MockAdapterMockRecorder) SetDatabase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDatabase", reflect.TypeOf((*MockAdapter)(nil).SetDatabase), arg0)
}

// ShowColumnsCtx mocks base method.
func (m *MockAdapter) ShowColumnsCtx(arg0 context.Context) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowColumnsCtx", arg0)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ShowColumnsCtx indicates an expected call of ShowColumnsCtx.
func (mr *MockAdapterMockRecorder) ShowColumnsCtx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowColumnsCtx", reflect.TypeOf((*MockAdapter)(nil).ShowColumnsCtx), arg0)
}

// ShowTable mocks base method.
func (m *MockAdapter) ShowTable(arg0, arg1 string) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowTable", arg0, arg1)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ShowTable indicates an expected call of ShowTable.
func (mr *MockAdapterMockRecorder) ShowTable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowTable", reflect.TypeOf((*MockAdapter)(nil).ShowTable), arg0, arg1)
}

// ShowTableCtx mocks base method.
func (m *MockAdapter) ShowTableCtx(arg0 context.Context, arg1, arg2 string) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowTableCtx", arg0, arg1, arg2)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ShowTableCtx indicates an expected call of ShowTableCtx.
func (mr *MockAdapterMockRecorder) ShowTableCtx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowTableCtx", reflect.TypeOf((*MockAdapter)(nil).ShowTableCtx), arg0, arg1, arg2)
}

// TableClause mocks base method.
func (m *MockAdapter) TableClause() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableClause")
	ret0, _ := ret[0].(string)
	return ret0
}

// TableClause indicates an expected call of TableClause.
func (mr *MockAdapterMockRecorder) TableClause() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableClause", reflect.TypeOf((*MockAdapter)(nil).TableClause))
}

// TableOrderBy mocks base method.
func (m *MockAdapter) TableOrderBy(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableOrderBy", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// TableOrderBy indicates an expected call of TableOrderBy.
func (mr *MockAdapterMockRecorder) TableOrderBy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableOrderBy", reflect.TypeOf((*MockAdapter)(nil).TableOrderBy), arg0)
}

// TablePermissions mocks base method.
func (m *MockAdapter) TablePermissions(arg0, arg1, arg2, arg3, arg4 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TablePermissions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(bool)
	return ret0
}

// TablePermissions indicates an expected call of TablePermissions.
func (mr *MockAdapterMockRecorder) TablePermissions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TablePermissions", reflect.TypeOf((*MockAdapter)(nil).TablePermissions), arg0, arg1, arg2, arg3, arg4)
}

// TableWhere mocks base method.
func (m *MockAdapter) TableWhere(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableWhere", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// TableWhere indicates an expected call of TableWhere.
func (mr *MockAdapterMockRecorder) TableWhere(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableWhere", reflect.TypeOf((*MockAdapter)(nil).TableWhere), arg0)
}

// Update mocks base method.
func (m *MockAdapter) Update(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdapterMockRecorder) Update(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdapter)(nil).Update), varargs...)
}

// UpdateCtx mocks base method.
func (m *MockAdapter) UpdateCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// UpdateCtx indicates an expected call of UpdateCtx.
func (mr *MockAdapterMockRecorder) UpdateCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCtx", reflect.TypeOf((*MockAdapter)(nil).UpdateCtx), varargs...)
}

// UpdateSQL mocks base method.
func (m *MockAdapter) UpdateSQL(arg0, arg1, arg2, arg3 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSQL", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	return ret0
}

// UpdateSQL indicates an expected call of UpdateSQL.
func (mr *MockAdapterMockRecorder) UpdateSQL(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSQL", reflect.TypeOf((*MockAdapter)(nil).UpdateSQL), arg0, arg1, arg2, arg3)
}

// UpdateWithTransaction mocks base method.
func (m *MockAdapter) UpdateWithTransaction(arg0 *sql.Tx, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateWithTransaction", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// UpdateWithTransaction indicates an expected call of UpdateWithTransaction.
func (mr *MockAdapterMockRecorder) UpdateWithTransaction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTransaction", reflect.TypeOf((*MockAdapter)(nil).UpdateWithTransaction), varargs...)
}

// WhereByRequest mocks base method.
func (m *MockAdapter) WhereByRequest(arg0 *http.Request, arg1 int) (string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WhereByRequest", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WhereByRequest indicates an expected call of WhereByRequest.
func (mr *MockAdapterMockRecorder) WhereByRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhereByRequest", reflect.TypeOf((*MockAdapter)(nil).WhereByRequest), arg0, arg1)
}
