// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: CatalogQuerier)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCatalogQuerier is a mock of CatalogQuerier interface.
type MockCatalogQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogQuerierMockRecorder
}

// MockCatalogQuerierMockRecorder is the mock recorder for MockCatalogQuerier.
type MockCatalogQuerierMockRecorder struct {
	mock *MockCatalogQuerier
}

// NewMockCatalogQuerier creates a new mock instance.
func NewMockCatalogQuerier(ctrl *gomock.Controller) *MockCatalogQuerier {
	mock := &MockCatalogQuerier{ctrl: ctrl}
	mock.recorder = &MockCatalogQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogQuerier) EXPECT() *MockCatalogQuerierMockRecorder {
	return m.recorder
}

// DatabaseClause mocks base method.
func (m *MockCatalogQuerier) DatabaseClause(arg0 *http.Request) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseClause", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DatabaseClause indicates an expected call of DatabaseClause.
func (mr *MockCatalogQuerierMockRecorder) DatabaseClause(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseClause", reflect.TypeOf((*MockCatalogQuerier)(nil).DatabaseClause), arg0)
}

// DatabaseOrderBy mocks base method.
func (m *MockCatalogQuerier) DatabaseOrderBy(arg0 string, arg1 bool) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseOrderBy", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// DatabaseOrderBy indicates an expected call of DatabaseOrderBy.
func (mr *MockCatalogQuerierMockRecorder) DatabaseOrderBy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseOrderBy", reflect.TypeOf((*MockCatalogQuerier)(nil).DatabaseOrderBy), arg0, arg1)
}

// DatabaseWhere mocks base method.
func (m *MockCatalogQuerier) DatabaseWhere(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseWhere", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// DatabaseWhere indicates an expected call of DatabaseWhere.
func (mr *MockCatalogQuerierMockRecorder) DatabaseWhere(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseWhere", reflect.TypeOf((*MockCatalogQuerier)(nil).DatabaseWhere), arg0)
}

// SchemaClause mocks base method.
func (m *MockCatalogQuerier) SchemaClause(arg0 *http.Request) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaClause", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// SchemaClause indicates an expected call of SchemaClause.
func (mr *MockCatalogQuerierMockRecorder) SchemaClause(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaClause", reflect.TypeOf((*MockCatalogQuerier)(nil).SchemaClause), arg0)
}

// SchemaOrderBy mocks base method.
func (m *MockCatalogQuerier) SchemaOrderBy(arg0 string, arg1 bool) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaOrderBy", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// SchemaOrderBy indicates an expected call of SchemaOrderBy.
func (mr *MockCatalogQuerierMockRecorder) SchemaOrderBy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaOrderBy", reflect.TypeOf((*MockCatalogQuerier)(nil).SchemaOrderBy), arg0, arg1)
}

// SchemaTablesClause mocks base method.
func (m *MockCatalogQuerier) SchemaTablesClause() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaTablesClause")
	ret0, _ := ret[0].(string)
	return ret0
}

// SchemaTablesClause indicates an expected call of SchemaTablesClause.
func (mr *MockCatalogQuerierMockRecorder) SchemaTablesClause() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaTablesClause", reflect.TypeOf((*MockCatalogQuerier)(nil).SchemaTablesClause))
}

// SchemaTablesOrderBy mocks base method.
func (m *MockCatalogQuerier) SchemaTablesOrderBy(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaTablesOrderBy", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// SchemaTablesOrderBy indicates an expected call of SchemaTablesOrderBy.
func (mr *MockCatalogQuerierMockRecorder) SchemaTablesOrderBy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaTablesOrderBy", reflect.TypeOf((*MockCatalogQuerier)(nil).SchemaTablesOrderBy), arg0)
}

// SchemaTablesWhere mocks base method.
func (m *MockCatalogQuerier) SchemaTablesWhere(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaTablesWhere", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// SchemaTablesWhere indicates an expected call of SchemaTablesWhere.
func (mr *MockCatalogQuerierMockRecorder) SchemaTablesWhere(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaTablesWhere", reflect.TypeOf((*MockCatalogQuerier)(nil).SchemaTablesWhere), arg0)
}

// TableClause mocks base method.
func (m *MockCatalogQuerier) TableClause() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableClause")
	ret0, _ := ret[0].(string)
	return ret0
}

// TableClause indicates an expected call of TableClause.
func (mr *MockCatalogQuerierMockRecorder) TableClause() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableClause", reflect.TypeOf((*MockCatalogQuerier)(nil).TableClause))
}

// TableOrderBy mocks base method.
func (m *MockCatalogQuerier) TableOrderBy(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableOrderBy", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// TableOrderBy indicates an expected call of TableOrderBy.
func (mr *MockCatalogQuerierMockRecorder) TableOrderBy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableOrderBy", reflect.TypeOf((*MockCatalogQuerier)(nil).TableOrderBy), arg0)
}

// TableWhere mocks base method.
func (m *MockCatalogQuerier) TableWhere(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableWhere", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// TableWhere indicates an expected call of TableWhere.
func (mr *MockCatalogQuerierMockRecorder) TableWhere(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableWhere", reflect.TypeOf((*MockCatalogQuerier)(nil).TableWhere), arg0)
}
