// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: DatabaseRegistry)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabaseRegistry is a mock of DatabaseRegistry interface.
type MockDatabaseRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseRegistryMockRecorder
}

// MockDatabaseRegistryMockRecorder is the mock recorder for MockDatabaseRegistry.
type MockDatabaseRegistryMockRecorder struct {
	mock *MockDatabaseRegistry
}

// NewMockDatabaseRegistry creates a new mock instance.
func NewMockDatabaseRegistry(ctrl *gomock.Controller) *MockDatabaseRegistry {
	mock := &MockDatabaseRegistry{ctrl: ctrl}
	mock.recorder = &MockDatabaseRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseRegistry) EXPECT() *MockDatabaseRegistryMockRecorder {
	return m.recorder
}

// GetDatabase mocks base method.
func (m *MockDatabaseRegistry) GetDatabase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabase")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockDatabaseRegistryMockRecorder) GetDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabase", reflect.TypeOf((*MockDatabaseRegistry)(nil).GetDatabase))
}

// IsRegistered mocks base method.
func (m *MockDatabaseRegistry) IsRegistered(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRegistered", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRegistered indicates an expected call of IsRegistered.
func (mr *MockDatabaseRegistryMockRecorder) IsRegistered(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRegistered", reflect.TypeOf((*MockDatabaseRegistry)(nil).IsRegistered), arg0)
}

// PhysicalName mocks base method.
func (m *MockDatabaseRegistry) PhysicalName(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhysicalName", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// PhysicalName indicates an expected call of PhysicalName.
func (mr *MockDatabaseRegistryMockRecorder) PhysicalName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhysicalName", reflect.TypeOf((*MockDatabaseRegistry)(nil).PhysicalName), arg0)
}

// SetDatabase mocks base method.
func (m *MockDatabaseRegistry) SetDatabase(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDatabase", arg0)
}

// SetDatabase indicates an expected call of SetDatabase.
func (mr *MockDatabaseRegistryMockRecorder) SetDatabase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDatabase", reflect.TypeOf((*MockDatabaseRegistry)(nil).SetDatabase), arg0)
}
