// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: Dialect)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDialect is a mock of Dialect interface.
type MockDialect struct {
	ctrl     *gomock.Controller
	recorder *MockDialectMockRecorder
}

// MockDialectMockRecorder is the mock recorder for MockDialect.
type MockDialectMockRecorder struct {
	mock *MockDialect
}

// NewMockDialect creates a new mock instance.
func NewMockDialect(ctrl *gomock.Controller) *MockDialect {
	mock := &MockDialect{ctrl: ctrl}
	mock.recorder = &MockDialectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialect) EXPECT() *MockDialectMockRecorder {
	return m.recorder
}

// Placeholder mocks base method.
func (m *MockDialect) Placeholder(arg0 int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Placeholder", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Placeholder indicates an expected call of Placeholder.
func (mr *MockDialectMockRecorder) Placeholder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Placeholder", reflect.TypeOf((*MockDialect)(nil).Placeholder), arg0)
}

// QuoteIdentifier mocks base method.
func (m *MockDialect) QuoteIdentifier(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuoteIdentifier", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuoteIdentifier indicates an expected call of QuoteIdentifier.
func (mr *MockDialectMockRecorder) QuoteIdentifier(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteIdentifier", reflect.TypeOf((*MockDialect)(nil).QuoteIdentifier), arg0)
}
