// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: PermissionsChecker)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPermissionsChecker is a mock of PermissionsChecker interface.
type MockPermissionsChecker struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionsCheckerMockRecorder
}

// MockPermissionsCheckerMockRecorder is the mock recorder for MockPermissionsChecker.
type MockPermissionsCheckerMockRecorder struct {
	mock *MockPermissionsChecker
}

// NewMockPermissionsChecker creates a new mock instance.
func NewMockPermissionsChecker(ctrl *gomock.Controller) *MockPermissionsChecker {
	mock := &MockPermissionsChecker{ctrl: ctrl}
	mock.recorder = &MockPermissionsCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionsChecker) EXPECT() *MockPermissionsCheckerMockRecorder {
	return m.recorder
}

// FieldsPermissions mocks base method.
func (m *MockPermissionsChecker) FieldsPermissions(arg0 *http.Request, arg1, arg2, arg3, arg4, arg5 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FieldsPermissions", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FieldsPermissions indicates an expected call of FieldsPermissions.
func (mr *MockPermissionsCheckerMockRecorder) FieldsPermissions(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FieldsPermissions", reflect.TypeOf((*MockPermissionsChecker)(nil).FieldsPermissions), arg0, arg1, arg2, arg3, arg4, arg5)
}

// TablePermissions mocks base method.
func (m *MockPermissionsChecker) TablePermissions(arg0, arg1, arg2, arg3, arg4 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TablePermissions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(bool)
	return ret0
}

// TablePermissions indicates an expected call of TablePermissions.
func (mr *MockPermissionsCheckerMockRecorder) TablePermissions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TablePermissions", reflect.TypeOf((*MockPermissionsChecker)(nil).TablePermissions), arg0, arg1, arg2, arg3, arg4)
}
