// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: QueryRegistry)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	adapters "github.com/prest/prest/v2/adapters"
)

// MockQueryRegistry is a mock of QueryRegistry interface.
type MockQueryRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRegistryMockRecorder
}

// MockQueryRegistryMockRecorder is the mock recorder for MockQueryRegistry.
type MockQueryRegistryMockRecorder struct {
	mock *MockQueryRegistry
}

// NewMockQueryRegistry creates a new mock instance.
func NewMockQueryRegistry(ctrl *gomock.Controller) *MockQueryRegistry {
	mock := &MockQueryRegistry{ctrl: ctrl}
	mock.recorder = &MockQueryRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRegistry) EXPECT() *MockQueryRegistryMockRecorder {
	return m.recorder
}

// DeleteQuery mocks base method.
func (m *MockQueryRegistry) DeleteQuery(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuery", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuery indicates an expected call of DeleteQuery.
func (mr *MockQueryRegistryMockRecorder) DeleteQuery(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuery", reflect.TypeOf((*MockQueryRegistry)(nil).DeleteQuery), arg0, arg1, arg2, arg3)
}

// GetQuery mocks base method.
func (m *MockQueryRegistry) GetQuery(arg0 context.Context, arg1, arg2, arg3 string) (adapters.StoredQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(adapters.StoredQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockQueryRegistryMockRecorder) GetQuery(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*MockQueryRegistry)(nil).GetQuery), arg0, arg1, arg2, arg3)
}

// ImportFromFilesystem mocks base method.
func (m *MockQueryRegistry) ImportFromFilesystem(arg0 context.Context, arg1, arg2 string) (adapters.ImportReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportFromFilesystem", arg0, arg1, arg2)
	ret0, _ := ret[0].(adapters.ImportReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportFromFilesystem indicates an expected call of ImportFromFilesystem.
func (mr *MockQueryRegistryMockRecorder) ImportFromFilesystem(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportFromFilesystem", reflect.TypeOf((*MockQueryRegistry)(nil).ImportFromFilesystem), arg0, arg1, arg2)
}

// ListQueries mocks base method.
func (m *MockQueryRegistry) ListQueries(arg0 context.Context, arg1, arg2 string) ([]adapters.StoredQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQueries", arg0, arg1, arg2)
	ret0, _ := ret[0].([]adapters.StoredQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQueries indicates an expected call of ListQueries.
func (mr *MockQueryRegistryMockRecorder) ListQueries(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQueries", reflect.TypeOf((*MockQueryRegistry)(nil).ListQueries), arg0, arg1, arg2)
}

// UpsertQuery mocks base method.
func (m *MockQueryRegistry) UpsertQuery(arg0 context.Context, arg1 adapters.StoredQuery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertQuery", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertQuery indicates an expected call of UpsertQuery.
func (mr *MockQueryRegistryMockRecorder) UpsertQuery(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertQuery", reflect.TypeOf((*MockQueryRegistry)(nil).UpsertQuery), arg0, arg1)
}
