// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: ReadinessChecker)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReadinessChecker is a mock of ReadinessChecker interface.
type MockReadinessChecker struct {
	ctrl     *gomock.Controller
	recorder *MockReadinessCheckerMockRecorder
}

// MockReadinessCheckerMockRecorder is the mock recorder for MockReadinessChecker.
type MockReadinessCheckerMockRecorder struct {
	mock *MockReadinessChecker
}

// NewMockReadinessChecker creates a new mock instance.
func NewMockReadinessChecker(ctrl *gomock.Controller) *MockReadinessChecker {
	mock := &MockReadinessChecker{ctrl: ctrl}
	mock.recorder = &MockReadinessCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadinessChecker) EXPECT() *MockReadinessCheckerMockRecorder {
	return m.recorder
}

// PingAll mocks base method.
func (m *MockReadinessChecker) PingAll(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingAll", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingAll indicates an expected call of PingAll.
func (mr *MockReadinessCheckerMockRecorder) PingAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingAll", reflect.TypeOf((*MockReadinessChecker)(nil).PingAll), arg0)
}
