// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: RequestQueryBuilder)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRequestQueryBuilder is a mock of RequestQueryBuilder interface.
type MockRequestQueryBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockRequestQueryBuilderMockRecorder
}

// MockRequestQueryBuilderMockRecorder is the mock recorder for MockRequestQueryBuilder.
type MockRequestQueryBuilderMockRecorder struct {
	mock *MockRequestQueryBuilder
}

// NewMockRequestQueryBuilder creates a new mock instance.
func NewMockRequestQueryBuilder(ctrl *gomock.Controller) *MockRequestQueryBuilder {
	mock := &MockRequestQueryBuilder{ctrl: ctrl}
	mock.recorder = &MockRequestQueryBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestQueryBuilder) EXPECT() *MockRequestQueryBuilderMockRecorder {
	return m.recorder
}

// CountByRequest mocks base method.
func (m *MockRequestQueryBuilder) CountByRequest(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByRequest indicates an expected call of CountByRequest.
func (mr *MockRequestQueryBuilderMockRecorder) CountByRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByRequest", reflect.TypeOf((*MockRequestQueryBuilder)(nil).CountByRequest), arg0)
}

// DistinctClause mocks base method.
func (m *MockRequestQueryBuilder) DistinctClause(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistinctClause", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistinctClause indicates an expected call of DistinctClause.
func (mr *MockRequestQueryBuilderMockRecorder) DistinctClause(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistinctClause", reflect.TypeOf((*MockRequestQueryBuilder)(nil).DistinctClause), arg0)
}

// GroupByClause mocks base method.
func (m *MockRequestQueryBuilder) GroupByClause(arg0 *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupByClause", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GroupByClause indicates an expected call of GroupByClause.
func (mr *MockRequestQueryBuilderMockRecorder) GroupByClause(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupByClause", reflect.TypeOf((*MockRequestQueryBuilder)(nil).GroupByClause), arg0)
}

// JoinByRequest mocks base method.
func (m *MockRequestQueryBuilder) JoinByRequest(arg0 *http.Request) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinByRequest", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinByRequest indicates an expected call of JoinByRequest.
func (mr *MockRequestQueryBuilderMockRecorder) JoinByRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinByRequest", reflect.TypeOf((*MockRequestQueryBuilder)(nil).JoinByRequest), arg0)
}

// OrderByRequest mocks base method.
func (m *MockRequestQueryBuilder) OrderByRequest(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderByRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderByRequest indicates an expected call of OrderByRequest.
func (mr *MockRequestQueryBuilderMockRecorder) OrderByRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderByRequest", reflect.TypeOf((*MockRequestQueryBuilder)(nil).OrderByRequest), arg0)
}

// PaginateIfPossible mocks base method.
func (m *MockRequestQueryBuilder) PaginateIfPossible(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaginateIfPossible", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PaginateIfPossible indicates an expected call of PaginateIfPossible.
func (mr *MockRequestQueryBuilderMockRecorder) PaginateIfPossible(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaginateIfPossible", reflect.TypeOf((*MockRequestQueryBuilder)(nil).PaginateIfPossible), arg0)
}

// ParseBatchInsertRequest mocks base method.
func (m *MockRequestQueryBuilder) ParseBatchInsertRequest(arg0 *http.Request) (string, string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseBatchInsertRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].([]interface{})
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ParseBatchInsertRequest indicates an expected call of ParseBatchInsertRequest.
func (mr *MockRequestQueryBuilderMockRecorder) ParseBatchInsertRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseBatchInsertRequest", reflect.TypeOf((*MockRequestQueryBuilder)(nil).ParseBatchInsertRequest), arg0)
}

// ParseInsertRequest mocks base method.
func (m *MockRequestQueryBuilder) ParseInsertRequest(arg0 *http.Request) (string, string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInsertRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].([]interface{})
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ParseInsertRequest indicates an expected call of ParseInsertRequest.
func (mr *MockRequestQueryBuilderMockRecorder) ParseInsertRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInsertRequest", reflect.TypeOf((*MockRequestQueryBuilder)(nil).ParseInsertRequest), arg0)
}

// ReturningByRequest mocks base method.
func (m *MockRequestQueryBuilder) ReturningByRequest(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturningByRequest", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReturningByRequest indicates an expected call of ReturningByRequest.
func (mr *MockRequestQueryBuilderMockRecorder) ReturningByRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturningByRequest", reflect.TypeOf((*MockRequestQueryBuilder)(nil).ReturningByRequest), arg0)
}

// SetByRequest mocks base method.
func (m *MockRequestQueryBuilder) SetByRequest(arg0 *http.Request, arg1 int) (string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByRequest", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetByRequest indicates an expected call of SetByRequest.
func (mr *MockRequestQueryBuilderMockRecorder) SetByRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByRequest", reflect.TypeOf((*MockRequestQueryBuilder)(nil).SetByRequest), arg0, arg1)
}

// WhereByRequest mocks base method.
func (m *MockRequestQueryBuilder) WhereByRequest(arg0 *http.Request, arg1 int) (string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WhereByRequest", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WhereByRequest indicates an expected call of WhereByRequest.
func (mr *MockRequestQueryBuilderMockRecorder) WhereByRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhereByRequest", reflect.TypeOf((*MockRequestQueryBuilder)(nil).WhereByRequest), arg0, arg1)
}
