// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: ScriptPermissionsChecker)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockScriptPermissionsChecker is a mock of ScriptPermissionsChecker interface.
type MockScriptPermissionsChecker struct {
	ctrl     *gomock.Controller
	recorder *MockScriptPermissionsCheckerMockRecorder
}

// MockScriptPermissionsCheckerMockRecorder is the mock recorder for MockScriptPermissionsChecker.
type MockScriptPermissionsCheckerMockRecorder struct {
	mock *MockScriptPermissionsChecker
}

// NewMockScriptPermissionsChecker creates a new mock instance.
func NewMockScriptPermissionsChecker(ctrl *gomock.Controller) *MockScriptPermissionsChecker {
	mock := &MockScriptPermissionsChecker{ctrl: ctrl}
	mock.recorder = &MockScriptPermissionsCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptPermissionsChecker) EXPECT() *MockScriptPermissionsCheckerMockRecorder {
	return m.recorder
}

// ScriptPermissions mocks base method.
func (m *MockScriptPermissionsChecker) ScriptPermissions(arg0, arg1, arg2, arg3, arg4 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScriptPermissions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ScriptPermissions indicates an expected call of ScriptPermissions.
func (mr *MockScriptPermissionsCheckerMockRecorder) ScriptPermissions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScriptPermissions", reflect.TypeOf((*MockScriptPermissionsChecker)(nil).ScriptPermissions), arg0, arg1, arg2, arg3, arg4)
}
