// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: ScriptRunner)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockScriptRunner is a mock of ScriptRunner interface.
type MockScriptRunner struct {
	ctrl     *gomock.Controller
	recorder *MockScriptRunnerMockRecorder
}

// MockScriptRunnerMockRecorder is the mock recorder for MockScriptRunner.
type MockScriptRunnerMockRecorder struct {
	mock *MockScriptRunner
}

// NewMockScriptRunner creates a new mock instance.
func NewMockScriptRunner(ctrl *gomock.Controller) *MockScriptRunner {
	mock := &MockScriptRunner{ctrl: ctrl}
	mock.recorder = &MockScriptRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptRunner) EXPECT() *MockScriptRunnerMockRecorder {
	return m.recorder
}

// GetScript mocks base method.
func (m *MockScriptRunner) GetScript(arg0, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScript", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScript indicates an expected call of GetScript.
func (mr *MockScriptRunnerMockRecorder) GetScript(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScript", reflect.TypeOf((*MockScriptRunner)(nil).GetScript), arg0, arg1, arg2)
}

// ParseScript mocks base method.
func (m *MockScriptRunner) ParseScript(arg0 string, arg1 map[string]interface{}) (string, []interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseScript", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParseScript indicates an expected call of ParseScript.
func (mr *MockScriptRunnerMockRecorder) ParseScript(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseScript", reflect.TypeOf((*MockScriptRunner)(nil).ParseScript), arg0, arg1)
}
