name: Bug Report 🐞
about: Something isn't working as expected? Here is the right place to report
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks** for taking the time to fill out this bug report!
        This info allows _prestd maintainers_ to diagnose (and fix!) your issue as quickly as possible.

        **before reporting certifies:**
        1. Please speak English, this is the language everybody of us can speak and write
        2. Please take a moment to search that an issue doesn't already exist here https://github.com/prest/prest/issues
        3. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report
  - type: dropdown
    id: project
    attributes:
      label: What project are you seeing the problem on?
      options:
        - API Server
        - BuildUI (Admin)
    validations:
      required: true
  - type: textarea
    id: project-version
    attributes:
      label: What version and environment are you using?
      value: |
        * version (or commit ref):
        * endpoint:
        * PostgreSQL version:
        * OS: [e.g. Debian Tid]:
        * Go/Node version:
        * Log gist url:
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      placeholder: e.g. I made a request to the endpoint `/databases` and it returned **error 500**
    validations:
      required: true
  - type: textarea
    id: bug-reproduce
    attributes:
      label: To Reproduce
      placeholder: |
        Steps to reproduce the behavior:
        1. Request to endpoint '...'
        2. See error
    validations:
      required: true
  - type: textarea
    id: bug-expected
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen
  - type: textarea
    id: bug-context-add
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here
