// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: QueryExecutor)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	adapters "github.com/prest/prest/v2/adapters"
)

// MockQueryExecutor is a mock of QueryExecutor interface.
type MockQueryExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockQueryExecutorMockRecorder
}

// MockQueryExecutorMockRecorder is the mock recorder for MockQueryExecutor.
type MockQueryExecutorMockRecorder struct {
	mock *MockQueryExecutor
}

// NewMockQueryExecutor creates a new mock instance.
func NewMockQueryExecutor(ctrl *gomock.Controller) *MockQueryExecutor {
	mock := &MockQueryExecutor{ctrl: ctrl}
	mock.recorder = &MockQueryExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryExecutor) EXPECT() *MockQueryExecutorMockRecorder {
	return m.recorder
}

// BatchInsertCopy mocks base method.
func (m *MockQueryExecutor) BatchInsertCopy(arg0, arg1, arg2 string, arg3 []string, arg4 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchInsertCopy", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// BatchInsertCopy indicates an expected call of BatchInsertCopy.
func (mr *MockQueryExecutorMockRecorder) BatchInsertCopy(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertCopy", reflect.TypeOf((*MockQueryExecutor)(nil).BatchInsertCopy), varargs...)
}

// BatchInsertCopyCtx mocks base method.
func (m *MockQueryExecutor) BatchInsertCopyCtx(arg0 context.Context, arg1, arg2, arg3 string, arg4 []string, arg5 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchInsertCopyCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// BatchInsertCopyCtx indicates an expected call of BatchInsertCopyCtx.
func (mr *MockQueryExecutorMockRecorder) BatchInsertCopyCtx(arg0, arg1, arg2, arg3, arg4 interface{}, arg5 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertCopyCtx", reflect.TypeOf((*MockQueryExecutor)(nil).BatchInsertCopyCtx), varargs...)
}

// BatchInsertValues mocks base method.
func (m *MockQueryExecutor) BatchInsertValues(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchInsertValues", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// BatchInsertValues indicates an expected call of BatchInsertValues.
func (mr *MockQueryExecutorMockRecorder) BatchInsertValues(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertValues", reflect.TypeOf((*MockQueryExecutor)(nil).BatchInsertValues), varargs...)
}

// BatchInsertValuesCtx mocks base method.
func (m *MockQueryExecutor) BatchInsertValuesCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchInsertValuesCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// BatchInsertValuesCtx indicates an expected call of BatchInsertValuesCtx.
func (mr *MockQueryExecutorMockRecorder) BatchInsertValuesCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertValuesCtx", reflect.TypeOf((*MockQueryExecutor)(nil).BatchInsertValuesCtx), varargs...)
}

// Delete mocks base method.
func (m *MockQueryExecutor) Delete(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQueryExecutorMockRecorder) Delete(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQueryExecutor)(nil).Delete), varargs...)
}

// DeleteCtx mocks base method.
func (m *MockQueryExecutor) DeleteCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// DeleteCtx indicates an expected call of DeleteCtx.
func (mr *MockQueryExecutorMockRecorder) DeleteCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCtx", reflect.TypeOf((*MockQueryExecutor)(nil).DeleteCtx), varargs...)
}

// ExecuteScripts mocks base method.
func (m *MockQueryExecutor) ExecuteScripts(arg0, arg1 string, arg2 []interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteScripts", arg0, arg1, arg2)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ExecuteScripts indicates an expected call of ExecuteScripts.
func (mr *MockQueryExecutorMockRecorder) ExecuteScripts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteScripts", reflect.TypeOf((*MockQueryExecutor)(nil).ExecuteScripts), arg0, arg1, arg2)
}

// ExecuteScriptsCtx mocks base method.
func (m *MockQueryExecutor) ExecuteScriptsCtx(arg0 context.Context, arg1, arg2 string, arg3 []interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteScriptsCtx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ExecuteScriptsCtx indicates an expected call of ExecuteScriptsCtx.
func (mr *MockQueryExecutorMockRecorder) ExecuteScriptsCtx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteScriptsCtx", reflect.TypeOf((*MockQueryExecutor)(nil).ExecuteScriptsCtx), arg0, arg1, arg2, arg3)
}

// Insert mocks base method.
func (m *MockQueryExecutor) Insert(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockQueryExecutorMockRecorder) Insert(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockQueryExecutor)(nil).Insert), varargs...)
}

// InsertCtx mocks base method.
func (m *MockQueryExecutor) InsertCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// InsertCtx indicates an expected call of InsertCtx.
func (mr *MockQueryExecutorMockRecorder) InsertCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCtx", reflect.TypeOf((*MockQueryExecutor)(nil).InsertCtx), varargs...)
}

// Query mocks base method.
func (m *MockQueryExecutor) Query(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockQueryExecutorMockRecorder) Query(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockQueryExecutor)(nil).Query), varargs...)
}

// QueryCount mocks base method.
func (m *MockQueryExecutor) QueryCount(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCount", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// QueryCount indicates an expected call of QueryCount.
func (mr *MockQueryExecutorMockRecorder) QueryCount(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCount", reflect.TypeOf((*MockQueryExecutor)(nil).QueryCount), varargs...)
}

// QueryCountCtx mocks base method.
func (m *MockQueryExecutor) QueryCountCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCountCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// QueryCountCtx indicates an expected call of QueryCountCtx.
func (mr *MockQueryExecutorMockRecorder) QueryCountCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCountCtx", reflect.TypeOf((*MockQueryExecutor)(nil).QueryCountCtx), varargs...)
}

// QueryCtx mocks base method.
func (m *MockQueryExecutor) QueryCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// QueryCtx indicates an expected call of QueryCtx.
func (mr *MockQueryExecutorMockRecorder) QueryCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCtx", reflect.TypeOf((*MockQueryExecutor)(nil).QueryCtx), varargs...)
}

// ShowColumnsCtx mocks base method.
func (m *MockQueryExecutor) ShowColumnsCtx(arg0 context.Context) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowColumnsCtx", arg0)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ShowColumnsCtx indicates an expected call of ShowColumnsCtx.
func (mr *MockQueryExecutorMockRecorder) ShowColumnsCtx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowColumnsCtx", reflect.TypeOf((*MockQueryExecutor)(nil).ShowColumnsCtx), arg0)
}

// ShowTable mocks base method.
func (m *MockQueryExecutor) ShowTable(arg0, arg1 string) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowTable", arg0, arg1)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ShowTable indicates an expected call of ShowTable.
func (mr *MockQueryExecutorMockRecorder) ShowTable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowTable", reflect.TypeOf((*MockQueryExecutor)(nil).ShowTable), arg0, arg1)
}

// ShowTableCtx mocks base method.
func (m *MockQueryExecutor) ShowTableCtx(arg0 context.Context, arg1, arg2 string) adapters.Scanner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowTableCtx", arg0, arg1, arg2)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// ShowTableCtx indicates an expected call of ShowTableCtx.
func (mr *MockQueryExecutorMockRecorder) ShowTableCtx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowTableCtx", reflect.TypeOf((*MockQueryExecutor)(nil).ShowTableCtx), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockQueryExecutor) Update(arg0 string, arg1 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQueryExecutorMockRecorder) Update(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQueryExecutor)(nil).Update), varargs...)
}

// UpdateCtx mocks base method.
func (m *MockQueryExecutor) UpdateCtx(arg0 context.Context, arg1 string, arg2 ...interface{}) adapters.Scanner {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateCtx", varargs...)
	ret0, _ := ret[0].(adapters.Scanner)
	return ret0
}

// UpdateCtx indicates an expected call of UpdateCtx.
func (mr *MockQueryExecutorMockRecorder) UpdateCtx(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCtx", reflect.TypeOf((*MockQueryExecutor)(nil).UpdateCtx), varargs...)
}
