// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prest/prest/v2/adapters (interfaces: SQLBuilder)

// Package mockgen is a generated GoMock package.
package mockgen

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSQLBuilder is a mock of SQLBuilder interface.
type MockSQLBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockSQLBuilderMockRecorder
}

// MockSQLBuilderMockRecorder is the mock recorder for MockSQLBuilder.
type MockSQLBuilderMockRecorder struct {
	mock *MockSQLBuilder
}

// NewMockSQLBuilder creates a new mock instance.
func NewMockSQLBuilder(ctrl *gomock.Controller) *MockSQLBuilder {
	mock := &MockSQLBuilder{ctrl: ctrl}
	mock.recorder = &MockSQLBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLBuilder) EXPECT() *MockSQLBuilderMockRecorder {
	return m.recorder
}

// DeleteSQL mocks base method.
func (m *MockSQLBuilder) DeleteSQL(arg0, arg1, arg2 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSQL", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	return ret0
}

// DeleteSQL indicates an expected call of DeleteSQL.
func (mr *MockSQLBuilderMockRecorder) DeleteSQL(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSQL", reflect.TypeOf((*MockSQLBuilder)(nil).DeleteSQL), arg0, arg1, arg2)
}

// InsertSQL mocks base method.
func (m *MockSQLBuilder) InsertSQL(arg0, arg1, arg2, arg3, arg4 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSQL", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	return ret0
}

// InsertSQL indicates an expected call of InsertSQL.
func (mr *MockSQLBuilderMockRecorder) InsertSQL(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSQL", reflect.TypeOf((*MockSQLBuilder)(nil).InsertSQL), arg0, arg1, arg2, arg3, arg4)
}

// SelectFields mocks base method.
func (m *MockSQLBuilder) SelectFields(arg0 []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectFields", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectFields indicates an expected call of SelectFields.
func (mr *MockSQLBuilderMockRecorder) SelectFields(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectFields", reflect.TypeOf((*MockSQLBuilder)(nil).SelectFields), arg0)
}

// SelectSQL mocks base method.
func (m *MockSQLBuilder) SelectSQL(arg0, arg1, arg2, arg3 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectSQL", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectSQL indicates an expected call of SelectSQL.
func (mr *MockSQLBuilderMockRecorder) SelectSQL(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectSQL", reflect.TypeOf((*MockSQLBuilder)(nil).SelectSQL), arg0, arg1, arg2, arg3)
}

// UpdateSQL mocks base method.
func (m *MockSQLBuilder) UpdateSQL(arg0, arg1, arg2, arg3 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSQL", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	return ret0
}

// UpdateSQL indicates an expected call of UpdateSQL.
func (mr *MockSQLBuilderMockRecorder) UpdateSQL(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSQL", reflect.TypeOf((*MockSQLBuilder)(nil).UpdateSQL), arg0, arg1, arg2, arg3)
}
