version: "3"
services:

  prestd:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:postgres
    environment:
      - PREST_DEBUG=true # remove comment for enable DEBUG mode (disable JWT)
      - PREST_CONF=/opt/prestd/prest.toml
      - PREST_PG_HOST=localhost
      - PREST_PG_USER=prest
      - PREST_PG_PASS=prest
      - PREST_PG_DATABASE=prest
      - PREST_PG_PORT=5432
      - PREST_JWT_DEFAULT=false # remove if need jwt
      - PREST_SSL_MODE=disable

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=prest
      - POSTGRES_DB=prest
      - POSTGRES_PASSWORD=prest

# Persist database information after your VM shuts down (just these two lines!)
volumes:
  postgres_data:
