apiVersion: v1
kind: Service
metadata:
  labels:
    app: prest
  name: prest
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: prest
  type: LoadBalancer
