name: test
run-name: test code

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: build
    container: golang:latest
    defaults:
      run:
        shell: bash
        working-directory: /__w/prest/prest
    env:
      PREST_PG_HOST: postgres
      PREST_PG_DATABASE: prest-test
      PREST_PG_USER: postgres
      PREST_PG_PASS: postgres
      PREST_PG_PORT: 5432
      PREST_SSL_MODE: disable
      PREST_CONF: /__w/prest/prest/testdata/prest.toml
      PREST_MIGRATIONS: /__w/prest/prest/testdata/migrations
      PREST_QUERIES_LOCATION: /__w/prest/prest/testdata/queries
      BE_CRASHER: 1
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20.8
      - run: go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: pREST Test
        run: env go test -race -covermode=atomic -coverprofile=./coverage.out ./...

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.out
